### ISSUE TITLE
Video and audio types are not supported

### ISSUE THREAD

**Issue by mnuriyumusak** [ajith-ab/react-native-file-share-intent#20]
When I try to share ogg, mp3 or mpeg file it says "type is not support". Why this is happening? Is there any way to solve this problem.

**Comment by flo-wolf** [comment]
Any update on this?

**Comment by flo-wolf** [comment]
@mnuriyumusak I have solved this by editing the getFilepath function in RNFileShareIntentModule.java manually to the following:

>  @ReactMethod
>   public void getFilepath(Callback successCallback) {
>     Activity mActivity = getCurrentActivity();
>     
>     if(mActivity == null) { return; }
>     
>     Intent intent = mActivity.getIntent();
>     String action = intent.getAction();
>     String type = intent.getType();
> 
>     Boolean isUriFile = (type != null && (type.startsWith("image/") || type.startsWith("video/") || type.startsWith("application/") || type.startsWith("audio/")));
> 
>     if (Intent.ACTION_SEND.equals(action) && type != null) {
>       if ("text/plain".equals(type)) {
>         String input = intent.getStringExtra(Intent.EXTRA_TEXT);
>         successCallback.invoke(input);
>       } else if (isUriFile) {
>         Uri fileUri = (Uri) intent.getParcelableExtra(Intent.EXTRA_STREAM);
>         if (fileUri != null) {
>           successCallback.invoke(fileUri.toString());
>         }
>       }else {
>         Toast.makeText(reactContext, "Type is not support", Toast.LENGTH_SHORT).show();
>       }
>     } else if (Intent.ACTION_SEND_MULTIPLE.equals(action) && type != null) {
>         if (isUriFile) {
>           ArrayList<Uri> fileUris = intent.getParcelableArrayListExtra(Intent.EXTRA_STREAM);
>           if (fileUris != null) {
>             String completeString = new String();
>             for (Uri uri: fileUris) {
>               completeString += uri.toString() + ",";
>             }
>             successCallback.invoke(completeString);
>           }
>         } else {
>           Toast.makeText(reactContext, "Type is not support", Toast.LENGTH_SHORT).show();
>         }
>     }
>   }

you can now add whatever mime types you want by editing the conditions for setting isUriFile.

Note that it is really bad practice to edit package files, since npm install would override the changes and usually node_modules are not being commited. The best way would be to create a pull request here (or fork) and introduce these changes for any file type. The mime types specified in the android manifest already dictate what to allow and what not, no need to do that code based.

**Comment by flo-wolf** [comment]
**Update:**
I have forked this repo to allow all file types to be processed by this package. Use your Mime types in your intent filter inside of AndroidManifest.xml to filter them.

https://github.com/flo-wolf/react-native-file-share-intent

**Comment by ajith-ab** [comment]
i ve created a new package  with all new features please look [react-native-receive-sharing-intent](https://www.npmjs.com/package/react-native-receive-sharing-intent)
